/**
 * Editor-related constants
 * Centralized location for all magic numbers and configuration values
 */

export const EDITOR_CONSTANTS = {
  // Timing constants
  TYPING_IDLE_THRESHOLD_MS: 1000,
  RENDER_DEBOUNCE_MS: 400,
  FINAL_SYNC_DELAY_MS: 100,
  
  // File management
  MAX_RECENT_FILES: 10,
  TEMP_PDFS_TO_KEEP: 10,
  
  // UI constants
  DEFAULT_EDITOR_SIZE: 50,
  DEFAULT_PREVIEW_SIZE: 50,
  MIN_PANEL_SIZE: 20,
  MAX_PANEL_SIZE: 75,
  COLLAPSED_PANEL_SIZE: 0,
  
  // Session management
  SESSION_SAVE_DEBOUNCE_MS: 500,
  
  // Toast durations
  TOAST_DURATION_SUCCESS: 3000,
  TOAST_DURATION_ERROR: 5000,
  TOAST_DURATION_WARNING: 4000,
  TOAST_DURATION_INFO: 3000,
  
  // Image handling
  DEFAULT_IMAGE_WIDTH: '60%',
  DEFAULT_IMAGE_ALIGNMENT: 'center',
  
  // Search panel
  SEARCH_PANEL_TOP: true,
  SEARCH_PANEL_CASE_SENSITIVE: false,
} as const;

export const TIMING_CONSTANTS = {
  TYPING_IDLE_THRESHOLD_MS: EDITOR_CONSTANTS.TYPING_IDLE_THRESHOLD_MS,
  RENDER_DEBOUNCE_MS: EDITOR_CONSTANTS.RENDER_DEBOUNCE_MS,
  FINAL_SYNC_DELAY_MS: EDITOR_CONSTANTS.FINAL_SYNC_DELAY_MS,
} as const;

export const UI_CONSTANTS = {
  DEFAULT_EDITOR_SIZE: EDITOR_CONSTANTS.DEFAULT_EDITOR_SIZE,
  DEFAULT_PREVIEW_SIZE: EDITOR_CONSTANTS.DEFAULT_PREVIEW_SIZE,
  MIN_PANEL_SIZE: EDITOR_CONSTANTS.MIN_PANEL_SIZE,
  MAX_PANEL_SIZE: EDITOR_CONSTANTS.MAX_PANEL_SIZE,
  COLLAPSED_PANEL_SIZE: EDITOR_CONSTANTS.COLLAPSED_PANEL_SIZE,
} as const;

export const FILE_CONSTANTS = {
  MAX_RECENT_FILES: EDITOR_CONSTANTS.MAX_RECENT_FILES,
  TEMP_PDFS_TO_KEEP: EDITOR_CONSTANTS.TEMP_PDFS_TO_KEEP,
} as const;

export const SESSION_CONSTANTS = {
  SAVE_DEBOUNCE_MS: EDITOR_CONSTANTS.SESSION_SAVE_DEBOUNCE_MS,
} as const;

export const TOAST_CONSTANTS = {
  SUCCESS_DURATION: EDITOR_CONSTANTS.TOAST_DURATION_SUCCESS,
  ERROR_DURATION: EDITOR_CONSTANTS.TOAST_DURATION_ERROR,
  WARNING_DURATION: EDITOR_CONSTANTS.TOAST_DURATION_WARNING,
  INFO_DURATION: EDITOR_CONSTANTS.TOAST_DURATION_INFO,
} as const;

export const IMAGE_CONSTANTS = {
  DEFAULT_WIDTH: EDITOR_CONSTANTS.DEFAULT_IMAGE_WIDTH,
  DEFAULT_ALIGNMENT: EDITOR_CONSTANTS.DEFAULT_IMAGE_ALIGNMENT,
} as const;

export const SEARCH_CONSTANTS = {
  PANEL_TOP: EDITOR_CONSTANTS.SEARCH_PANEL_TOP,
  CASE_SENSITIVE: EDITOR_CONSTANTS.SEARCH_PANEL_CASE_SENSITIVE,
} as const;